development:
  adapter: async

test:
  adapter: test

production:
  adapter: postgresql
  database: blog_cable_production
  username: postgres
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
  host: localhost
