default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_development
  username: postgres
  password: <%= ENV['DEV_DATABASE_PASSWORD'] %> # Configure no seu ambiente local

test:
  <<: *default
  database: blog_test
  username: postgres
  password: <%= ENV['TEST_DATABASE_PASSWORD'] %> # Configure no seu ambiente local

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  cable:
    adapter: postgresql
    database: blog_cable_production
    username: <%= ENV['PRODUCTION_DATABASE_USERNAME'] || "postgres" %>
    password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
    host: <%= ENV['PRODUCTION_DATABASE_HOST'] || "localhost" %>
